# -*- coding: utf-8 -*-
"""Deep Learning_UTS_A32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11u2gxjknn0BTg-M8-Zx-lcIV5lj7ktaA
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

import numpy as np
import matplotlib.pyplot as plt
import cv2 # Akan digunakan nanti untuk memproses gambar tulisan tangan
import os # Akan digunakan untuk memuat file gambar

# Pastikan versi TensorFlow yang digunakan
print("TensorFlow Version:", tf.__version__)

(x_train_orig, y_train_orig), (x_test_orig, y_test_orig) = mnist.load_data()

print(f"Bentuk data latih (x_train_orig): {x_train_orig.shape}")
print(f"Bentuk label latih (y_train_orig): {y_train_orig.shape}")
print(f"Bentuk data uji (x_test_orig): {x_test_orig.shape}")
print(f"Bentuk label uji (y_test_orig): {y_test_orig.shape}")

"""## PRA-PEMROSESAN DATA MNIST"""

img_rows, img_cols, channels = 28, 28, 1
num_classes = 10

x_train = x_train_orig.reshape(x_train_orig.shape[0], img_rows, img_cols, channels)
x_test = x_test_orig.reshape(x_test_orig.shape[0], img_rows, img_cols, channels)

input_shape = (img_rows, img_cols, channels)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
# Membagi dengan 255
x_train /= 255.0
x_test /= 255.0

# One-hot encoding labels
y_train = to_categorical(y_train_orig, num_classes)
y_test = to_categorical(y_test_orig, num_classes)

print("\n--- Setelah Pra-pemrosesan ---")
print(f"Bentuk x_train: {x_train.shape}")
print(f"Bentuk x_test: {x_test.shape}")
print(f"Bentuk y_train: {y_train.shape}")
print(f"Bentuk y_test: {y_test.shape}")
print(f"Input shape: {input_shape}")
print(f"Contoh label asli (y_train_orig[0]): {y_train_orig[0]}")
print(f"Contoh label one-hot (y_train[0]): {y_train[0]}")

plt.figure(figsize=(12, 6))
plt.suptitle("Contoh Citra dari Dataset MNIST (Setelah Pra-Pemrosesan)", fontsize=16)
for i in range(10):  # Menampilkan 10 gambar pertama
    plt.subplot(2, 5, i + 1)
    # Gunakan x_train_orig untuk visualisasi (karena imshow lebih mudah menangani 2D)
    # atau .squeeze() dari x_train yang sudah di-reshape
    plt.imshow(x_train[i].squeeze(), cmap='gray')
    plt.title(f"Label: {y_train_orig[i]}")
    plt.axis('off')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""## PEMBUATAN MODEL A"""

def create_model_A():
    model = Sequential()

    # Lapisan Konvolusi 1
    model.add(Conv2D(32, kernel_size=(3, 3),
                     activation='relu',
                     input_shape=input_shape,
                     name='conv2d_1'))
    model.add(MaxPooling2D(pool_size=(2, 2), name='maxpool_1'))

    # Lapisan Konvolusi 2
    model.add(Conv2D(64, (3, 3), activation='relu', name='conv2d_2'))
    model.add(MaxPooling2D(pool_size=(2, 2), name='maxpool_2'))

    # Lapisan Flatten
    model.add(Flatten(name='flatten'))

    # Lapisan Dense
    model.add(Dense(128, activation='relu', name='dense_1'))
    model.add(Dropout(0.5, name='dropout')) # Tambahkan Dropout untuk regularisasi

    # Lapisan Output
    model.add(Dense(num_classes, activation='softmax', name='output'))

    # Compile model
    model.compile(loss='categorical_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])

    return model

model_A = create_model_A()

# Tampilkan ringkasan model
print("--- Arsitektur Model A (CNN dari Nol) ---")
model_A.summary()

batch_size = 128
epochs = 10 # 10 epoch sudah cukup baik untuk MNIST

print("\n--- Memulai Pelatihan Model A ---")

history_A = model_A.fit(x_train, y_train,
                        batch_size=batch_size,
                        epochs=epochs,
                        verbose=1,
                        validation_data=(x_test, y_test))

print("--- Pelatihan Model A Selesai ---")

def plot_training_history(history, title):
    """Fungsi untuk mem-plot akurasi dan loss dari training history."""
    try:
        acc = history.history['accuracy']
        val_acc = history.history['val_accuracy']
        loss = history.history['loss']
        val_loss = history.history['val_loss']
    except KeyError:
        print("Error: Pastikan 'accuracy', 'val_accuracy', 'loss', dan 'val_loss' ada dalam history.")
        return

    epochs_range = range(len(acc))

    plt.figure(figsize=(14, 6))
    plt.suptitle(f"Training History - {title}", fontsize=16)

    # Plot Akurasi
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, acc, 'o-', label='Training Accuracy')
    plt.plot(epochs_range, val_acc, 'o-', label='Validation Accuracy')
    plt.legend(loc='lower right')
    plt.title('Training and Validation Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.grid(True)

    # Plot Loss
    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, loss, 'o-', label='Training Loss')
    plt.plot(epochs_range, val_loss, 'o-', label='Validation Loss')
    plt.legend(loc='upper right')
    plt.title('Training and Validation Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.grid(True)

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

print("\n--- Plot History Model A ---")
plot_training_history(history_A, "Model A (CNN dari Nol)")

score_A_mnist = model_A.evaluate(x_test, y_test, verbose=0)
print(f'--- Evaluasi Model A pada MNIST Test Set ---')
print(f'Test loss: {score_A_mnist[0]:.4f}')
print(f'Test accuracy: {score_A_mnist[1]:.4f} (atau {score_A_mnist[1]*100:.2f}%)')

# --- KONFIGURASI VALIDASI ---
IMG_DIR = 'uts'         # Nama folder
NIM_SEQ = [0, 9, 2]     # Urutan 3 digit NIM Anda (sesuai request: 092)
DIGIT_MAP = {           # Mapping angka ke nama file
    0: 'nol', 1: 'satu', 2: 'dua', 3: 'tiga', 4: 'empat',
    5: 'lima', 6: 'enam', 7: 'tujuh', 8: 'delapan', 9: 'sembilan'
}

# --- PROSES VALIDASI MODEL A ---
plt.figure(figsize=(10, 25)) # Ukuran plot disesuaikan untuk 10x3
plt.suptitle("Hasil Validasi Model A (CNN dari Nol)\nUrutan NIM: " + "".join([str(x) for x in NIM_SEQ]), fontsize=16, y=1.02)

total_correct_A = 0
total_samples = 30
subplot_idx = 1

print("Memulai validasi Model A...")

for row in range(1, 11): # Loop 10 baris (untuk 10 sampel per angka)
    for digit in NIM_SEQ: # Loop 3 kolom (sesuai urutan NIM 0, 9, 2)
        # 1. Buat path file (contoh: uts/nol_1.jpg)
        # Coba beberapa kemungkinan ekstensi jika .jpg tidak ketemu
        fname = f"{DIGIT_MAP[digit]}_{row}"
        path = os.path.join(f"{fname}.jpg")

        # 2. Pra-pemrosesan untuk Model A
        if os.path.exists(path):
            # a. Baca grayscale
            img_orig = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
            # b. Inversi warna (karena tulisan kita hitam di kertas putih)
            img_inv = cv2.bitwise_not(img_orig)
            # c. Resize ke 28x28
            img_resized = cv2.resize(img_inv, (28, 28), interpolation=cv2.INTER_AREA)
            # d. Normalisasi [0, 1]
            img_norm = img_resized.astype('float32') / 255.0
            # e. Reshape ke (1, 28, 28, 1)
            img_ready = img_norm.reshape(1, 28, 28, 1)

            # 3. Prediksi
            pred_prob = model_A.predict(img_ready, verbose=0)
            pred_label = np.argmax(pred_prob)

            # Hitung akurasi
            if pred_label == digit:
                total_correct_A += 1
                color = 'green' # Hijau jika benar
            else:
                color = 'red'   # Merah jika salah

            # 4. Visualisasi
            plt.subplot(10, 3, subplot_idx)
            plt.imshow(img_resized, cmap='gray') # Tampilkan gambar 28x28
            plt.title(f"Asli: {digit} | Pred: {pred_label}", color=color)
            plt.axis('off')
        else:
            # Jika file tidak ditemukan
            plt.subplot(10, 3, subplot_idx)
            plt.text(0.5, 0.5, "File Not Found", ha='center', va='center')
            plt.axis('off')
            print(f"Warning: File tidak ditemukan: {path}")

        subplot_idx += 1

plt.tight_layout()
plt.show()

print(f"\n--- Akurasi Akhir Model A: {(total_correct_A/total_samples)*100:.2f}% ({total_correct_A}/{total_samples}) ---")

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess

IMG_SIZE_B = 32
input_shape_B = (IMG_SIZE_B, IMG_SIZE_B, 3)

(x_train_orig, _), (x_test_orig, _) = mnist.load_data()

x_train_orig_4d = x_train_orig.reshape(x_train_orig.shape[0], img_rows, img_cols, channels)
x_test_orig_4d = x_test_orig.reshape(x_test_orig.shape[0], img_rows, img_cols, channels)

x_train_resized_B = tf.image.resize(x_train_orig_4d, (IMG_SIZE_B, IMG_SIZE_B))
x_test_resized_B = tf.image.resize(x_test_orig_4d, (IMG_SIZE_B, IMG_SIZE_B))

x_train_rgb_B = tf.image.grayscale_to_rgb(x_train_resized_B)
x_test_rgb_B = tf.image.grayscale_to_rgb(x_test_resized_B)

x_train_processed_B = resnet_preprocess(x_train_rgb_B)
x_test_processed_B = resnet_preprocess(x_test_rgb_B)

"""## MODEL B"""

def create_model_B():
    base_model = ResNet50(
        input_shape=input_shape_B,
        include_top=False,
        weights='imagenet'
    )

    base_model.trainable = False

    inputs = tf.keras.Input(shape=input_shape_B, name="input_B")

    x = base_model(inputs, training=False)

    x = tf.keras.layers.GlobalAveragePooling2D(name="global_avg_pool")(x)
    x = tf.keras.layers.Dropout(0.3, name="dropout_B")(x)
    outputs = tf.keras.layers.Dense(num_classes, activation='softmax', name="output_B")(x)

    model = Model(inputs, outputs)

    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model

model_B = create_model_B()
model_B.summary()

batch_size_B = 128
epochs_B = 10

print("\n--- Memulai Pelatihan Model B (ResNet50) ---")

history_B = model_B.fit(x_train_processed_B, y_train,
                        batch_size=batch_size_B,
                        epochs=epochs_B,
                        verbose=1,
                        validation_data=(x_test_processed_B, y_test))

print("--- Pelatihan Model B Selesai ---")

print("\n--- Plot History Model B ---")
plot_training_history(history_B, "Model B (Transfer Learning - ResNet50)")

score_B_mnist = model_B.evaluate(x_test_processed_B, y_test, verbose=0)
print(f'--- Evaluasi Model B pada MNIST Test Set ---')
print(f'Test loss: {score_B_mnist[0]:.4f}')
print(f'Test accuracy: {score_B_mnist[1]:.4f} (atau {score_B_mnist[1]*100:.2f}%)')

from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess

# --- KONFIGURASI VALIDASI ---
IMG_DIR = 'uts'         # Nama folder
NIM_SEQ = [0, 9, 2]     # Urutan 3 digit NIM
DIGIT_MAP = {           # Mapping angka ke nama file
    0: 'nol', 1: 'satu', 2: 'dua', 3: 'tiga', 4: 'empat',
    5: 'lima', 6: 'enam', 7: 'tujuh', 8: 'delapan', 9: 'sembilan'
}

# --- PROSES VALIDASI MODEL B ---
plt.figure(figsize=(10, 25))
plt.suptitle("Hasil Validasi Model B (ResNet50)\nUrutan NIM: " + "".join([str(x) for x in NIM_SEQ]), fontsize=16, y=1.02)

total_correct_B = 0
total_samples = 30
subplot_idx = 1

print("Memulai validasi Model B...")

for row in range(1, 11):
    for digit in NIM_SEQ:
        # 1. Buat path file
        fname = f"{DIGIT_MAP[digit]}_{row}"
        path = os.path.join(f"{fname}.jpg")

        # 2. Pra-pemrosesan untuk Model B (ResNet50)
        if os.path.exists(path):
            # a. Baca grayscale
            img_orig = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
            # b. Inversi warna
            img_inv = cv2.bitwise_not(img_orig)
            # c. Resize ke 32x32 (sesuai input Model B kita tadi)
            img_resized = cv2.resize(img_inv, (32, 32), interpolation=cv2.INTER_AREA)
            # d. Konversi ke RGB (3 channel)
            img_rgb = cv2.cvtColor(img_resized, cv2.COLOR_GRAY2RGB)
            # e. Preprocess bawaan ResNet50 (penting!)
            # Kita perlu copy agar tidak merubah gambar asli saat ditampilkan
            img_ready = resnet_preprocess(img_rgb.copy())
            # f. Expand dims menjadi (1, 32, 32, 3)
            img_ready = np.expand_dims(img_ready, axis=0)

            # 3. Prediksi
            pred_prob = model_B.predict(img_ready, verbose=0)
            pred_label = np.argmax(pred_prob)

            # Hitung akurasi
            if pred_label == digit:
                total_correct_B += 1
                color = 'green'
            else:
                color = 'red'

            # 4. Visualisasi
            plt.subplot(10, 3, subplot_idx)
            # Tampilkan gambar RGB yang sudah di-resize (sebelum preprocess resnet agar warnanya wajar dimata)
            plt.imshow(img_rgb)
            plt.title(f"Asli: {digit} | Pred: {pred_label}", color=color)
            plt.axis('off')
        else:
             plt.subplot(10, 3, subplot_idx)
             plt.text(0.5, 0.5, "File Not Found", ha='center', va='center')
             plt.axis('off')

        subplot_idx += 1

plt.tight_layout()
plt.show()

print(f"\n--- Akurasi Akhir Model B: {(total_correct_B/total_samples)*100:.2f}% ({total_correct_B}/{total_samples}) ---")

